version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - TZ=your_time_zone
      - WEBPASSWORD=[pass]
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "[port]:80"
      - "443:443"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
